
name: workflow1

on:
  workflow_dispatch:
    inputs:
      message:
        description: 'text a mostrar patata'
        required: true
        default: 'hello'
jobs:
  job1:
    name: job1
    runs-on: ubuntu-latest
    steps:
      - name: step 1
        run: |
          echo "${{github.event.inputs.message}}"